const types = @import("types");

pub const ReturnType = types.Message;
pub const api_method = "sendInvoice";

chat_id: types.ChatId,
title: []const u8,
description: []const u8,
payload: []const u8,
currency: []const u8,
prices: []const types.LabeledPrice,
message_thread_id: ?i32 = null,
direct_messages_topic_id: ?i32 = null,
provider_token: ?[]const u8 = null,
max_tip_amount: ?i32 = null,
suggested_tip_amounts: ?[]const i32 = null,
start_parameter: ?[]const u8 = null,
provider_data: ?[]const u8 = null,
photo_url: ?[]const u8 = null,
photo_size: ?i32 = null,
photo_width: ?i32 = null,
photo_height: ?i32 = null,
need_name: ?bool = null,
need_phone_number: ?bool = null,
need_email: ?bool = null,
need_shipping_address: ?bool = null,
send_phone_number_to_provider: ?bool = null,
send_email_to_provider: ?bool = null,
is_flexible: ?bool = null,
disable_notification: ?bool = null,
protect_content: ?bool = null,
allow_paid_broadcast: ?bool = null,
message_effect_id: ?[]const u8 = null,
suggested_post_parameters: ?types.SuggestedPostParameters = null,
reply_parameters: ?types.ReplyParameters = null,
reply_markup: ?types.InlineKeyboardMarkup = null,
