pub const PassportElementType = enum {
    personal_details,
    passport,
    driver_license,
    identity_card,
    internal_passport,
    address,
    utility_bill,
    bank_statement,
    rental_agreement,
    passport_registration,
    temporary_registration,
    phone_number,
    email,
};
