pub const BusinessBotRights = struct {
    can_reply: ?bool = null,
    can_read_messages: ?bool = null,
    can_delete_sent_messages: ?bool = null,
    can_delete_all_messages: ?bool = null,
    can_edit_name: ?bool = null,
    can_edit_bio: ?bool = null,
    can_edit_profile_photo: ?bool = null,
    can_edit_username: ?bool = null,
    can_change_gift_settings: ?bool = null,
    can_view_gifts_and_stars: ?bool = null,
    can_convert_gifts_to_stars: ?bool = null,
    can_transfer_and_upgrade_gifts: ?bool = null,
    can_transfer_stars: ?bool = null,
    can_manage_stories: ?bool = null,
};
