const enums = @import("enums");
const types = @import("types");

id: i64,
type: enums.ChatType,
title: ?[]const u8 = null,
username: ?[]const u8 = null,
first_name: ?[]const u8 = null,
last_name: ?[]const u8 = null,
is_forum: ?bool = null,
is_direct_messages: ?bool = null,
accent_color_id: i32,
max_reaction_count: i32,
photo: ?types.ChatPhoto = null,
active_usernames: ?[]const []const u8 = null,
birthdate: ?types.Birthdate = null,
business_intro: ?types.BusinessIntro = null,
business_location: ?types.BusinessLocation = null,
business_opening_hours: ?types.BusinessOpeningHours = null,
personal_chat: ?types.Chat = null,
parent_chat: ?types.Chat = null,
available_reactions: ?[]const types.ReactionType = null,
background_custom_emoji_id: ?[]const u8 = null,
profile_accent_color_id: ?i32 = null,
profile_background_custom_emoji_id: ?[]const u8 = null,
emoji_status_custom_emoji_id: ?[]const u8 = null,
emoji_status_expiration_date: ?i32 = null,
bio: ?[]const u8 = null,
has_private_forwards: ?bool = null,
has_restricted_voice_and_video_messages: ?bool = null,
join_to_send_messages: ?bool = null,
join_by_request: ?bool = null,
description: ?[]const u8 = null,
invite_link: ?[]const u8 = null,
pinned_message: ?types.Message = null,
permissions: ?types.ChatPermissions = null,
accepted_gift_types: ?[]const enums.AcceptedGiftTypes = null,
can_send_paid_media: ?bool = null,
slow_mode_delay: ?i32 = null,
unrestrict_boost_count: ?i32 = null,
message_auto_delete_time: ?i32 = null,
has_aggressive_anti_spam_enabled: ?bool = null,
has_hidden_members: ?bool = null,
has_protected_content: ?bool = null,
has_visible_history: ?bool = null,
sticker_set_name: ?[]const u8 = null,
can_set_sticker_set: ?bool = null,
custom_emoji_sticker_set_name: ?[]const u8 = null,
linked_chat_id: ?i64 = null,
location: ?types.ChatLocation = null,
rating: ?types.UserRating = null,
first_profile_audio: ?types.Audio = null,
unique_gift_colors: ?types.UniqueGiftColors = null,
paid_message_star_count: ?i32 = null,
