is_anonymous: bool,
can_manage_chat: bool,
can_delete_messages: bool,
can_manage_video_chats: bool,
can_restrict_members: bool,
can_promote_members: bool,
can_change_info: bool,
can_invite_users: bool,
can_post_stories: bool,
can_edit_stories: bool,
can_delete_stories: bool,
can_post_messages: ?bool = null,
can_edit_messages: ?bool = null,
can_pin_messages: ?bool = null,
can_manage_topics: ?bool = null,
can_manage_direct_messages: ?bool = null,
can_manage_tags: ?bool = null,
