const types = @import("../types.zig");

origin: types.MessageOrigin,
chat: ?types.Chat = null,
message_id: ?i32 = null,
link_preview_options: ?types.LinkPreviewOptions = null,
animation: ?types.Animation = null,
audio: ?types.Audio = null,
document: ?types.Document = null,
paid_media: ?types.PaidMediaInfo = null,
photo: ?[]const types.PhotoSize = null,
sticker: ?types.Sticker = null,
story: ?types.Story = null,
video: ?types.Video = null,
video_note: ?types.VideoNote = null,
voice: ?types.Voice = null,
has_media_spoiler: ?bool = null,
checklist: ?types.Checklist = null,
contact: ?types.Contact = null,
dice: ?types.Dice = null,
game: ?types.Game = null,
giveaway: ?types.Giveaway = null,
giveaway_winners: ?types.GiveawayWinners = null,
invoice: ?types.Invoice = null,
location: ?types.Location = null,
poll: ?types.Poll = null,
venue: ?types.Venue = null,
