const enums = @import("enums");
const types = @import("types");

id: []const u8,
question: []const u8,
question_entities: ?[]const types.MessageEntity = null,
options: []const types.PollOption,
total_voter_count: i32,
is_closed: bool,
is_anonymous: bool,
type: enums.PollType,
allows_multiple_answers: bool,
allows_revoting: bool,
members_only: bool,
country_codes: ?[]const []const u8 = null,
correct_option_ids: ?[]const i32 = null,
explanation: ?[]const u8 = null,
explanation_entities: ?[]const types.MessageEntity = null,
explanation_media: ?types.PollMedia = null,
open_period: ?i32 = null,
close_date: ?i32 = null,
description: ?[]const u8 = null,
description_entities: ?[]const types.MessageEntity = null,
media: ?types.PollMedia = null,
