const types = @import("types");

business_connection_id: ?[]const u8 = null,
chat_id: types.ChatId,
message_thread_id: ?i32 = null,
direct_messages_topic_id: ?i32 = null,
sticker: types.InputFile,
emoji: ?[]const u8 = null,
disable_notification: ?bool = null,
protect_content: ?bool = null,
allow_paid_broadcast: ?bool = null,
message_effect_id: ?[]const u8 = null,
suggested_post_parameters: ?types.SuggestedPostParameters = null,
reply_parameters: ?types.ReplyParameters = null,
reply_markup: ?types.ReplyMarkup = null,
