id: i64,
is_bot: bool,
first_name: []const u8,
last_name: ?[]const u8 = null,
username: ?[]const u8 = null,
language_code: ?[]const u8 = null,
is_premium: ?bool = null,
added_to_attachment_menu: ?bool = null,
can_join_groups: ?bool = null,
can_read_all_group_messages: ?bool = null,
supports_guest_queries: ?bool = null,
supports_inline_queries: ?bool = null,
can_connect_to_business: ?bool = null,
has_main_web_app: ?bool = null,
has_topics_enabled: ?bool = null,
allows_users_to_create_topics: ?bool = null,
can_manage_bots: ?bool = null,
supports_join_request_queries: ?bool = null,
